---
model:
    file_name: "models.gru_bahdanau"
    class_name: "GRU_Bahdanau"
    random_seed: 2019
    gru_hidden_states: 512
    attention_layer_units: 10
trainer:
    file_name: "trainers.trainer_transformer"
    class_name: "TrainerTransformer"
    epochs: 15
    batch_size: 4
    prefetch: 4
    shuffle_buffer_size: 4
    learning_rate: 0.0001
    #keras.losses
    loss_function: CategoricalCrossentropy
    #tf.optimizers
    optimizer: RMSprop
    accuracy: CategoricalAccuracy
    loss_metric: Mean
    training: True
    save_after: 3
vocabulary:
    vocabulary_size: 20000
    vocab_path: "data/vocab.pickle"
embedder:
    wv_path: "models/embeddings/google_wv"
    google_w2v_path: "models/embeddings/GoogleNews-vectors-negative300.bin"
    embeddings_matrix_path: "data/embeddings_matrix.pickle"
data_preprocessor:
    preprocess: False
    #max is 441
    chunks_included_train: 100
    #max is 47
    chunks_included_dev: 1
    cycle_length: 1
    spacy_model: "en_core_web_sm"
    squad_train_path: "data/train-v1.1.json"
    squad_dev_path: "data/dev-v1.1.json"
    sequence_length_input: 200
    sequence_length_target: 20
    folder_prefix_train: "data/train/"
    folder_prefix_dev: "data/dev/"
...